global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    http:
      tls: {}

providers:
  file:
    filename: "/etc/traefik/dynamic.yaml"
    watch: true
  docker:
    watch: true
    network: dev
    exposedByDefault: false
